### ISSUE TITLE
Do we need a LinuxBoot recipe?

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/riscv-os-a-see#23]
Comments on the Illustrative doc:

* The ARM LBBR-v1 profile doesn't appear to mandate any UEFI boot services.  Should we mandate all of these for all OS-A SEE profiles?
* This [UEFI runtime services section] is a longer list than what the ARM LBBR-v1 profile requires.  Do all of these UEFI services need to be mandated for all SEE-A profiles?
* Where do LinuxBoot requirements fit in? If BRS-I, the regular server class requirements do not hold good. Should it be separate recipe itself like ARM did?

I could see LinuxBoot to be a case of BRS-B (what is called VI here). If folks disagree because that's too open-ended, we can add a separate recipe

**Comment by paul-walmsley-sifive** [comment]
I think I may have been the one that originally commented about this.   Seems like we can put it off until a future revision of the specification or until someone who has a strong interest in this joins the group.

**Comment by andreiw** [comment]
Sounds good. Closing for now.
